import { MetropolitanRoad } from '@/types';

/**
 * PDF Kayanak Verisi: “Cadde_Bulvar.xlsx - Detay Veri Listesi.pdf”
 * "TÜM CADDE VE BULVAR LİSTESİ" tablosundan eksiksiz ve birebir aktarılmıştır.
 * Toplam Kayıt Sayısı: 154
 */
export const metropolitanRoads: MetropolitanRoad[] = [
  // --- AKSU (10 Kayıt) ---
  { id: 'ROAD-001', district: 'AKSU', roadName: 'YAŞAR SOBUTAY BULVARI -(LARA TURZ. YOLU)' },
  { id: 'ROAD-002', district: 'AKSU', roadName: 'İSMAİL OGAN CADDESİ' },
  { id: 'ROAD-003', district: 'AKSU', roadName: 'PINARLI ATATÜRK BULVARI' },
  { id: 'ROAD-004', district: 'AKSU', roadName: 'VEYSELLER CADDESİ' },
  { id: 'ROAD-005', district: 'AKSU', roadName: 'MİLLİ EGEMENLİK CADDESİ' },
  { id: 'ROAD-006', district: 'AKSU', roadName: 'MEVLANA CADDESİ' },
  { id: 'ROAD-007', district: 'AKSU', roadName: 'ALİCİKLER CADDESİ' },
  { id: 'ROAD-008', district: 'AKSU', roadName: 'GÜMÜŞLER CADDESİ' },
  { id: 'ROAD-009', district: 'AKSU', roadName: 'KARGILIDERE CADDESİ' },
  { id: 'ROAD-010', district: 'AKSU', roadName: 'LARA TURİZM YOLU' },

  // --- DÖŞEMEALTI (1 Kayıt) ---
  { id: 'ROAD-011', district: 'DÖŞEMEALTI', roadName: 'DÖŞEMEALTI_ATATÜRK CADDESİ' },

  // --- SERİK (3 Kayıt) ---
  { id: 'ROAD-012', district: 'SERİK', roadName: 'ATATÜRK CADDESİ' },
  { id: 'ROAD-013', district: 'SERİK', roadName: 'KİZDERESİ CADDESİ' },
  { id: 'ROAD-014', district: 'SERİK', roadName: 'PROF.DR.YAŞAR UÇAR CADDESİ' },

  // --- KORKUTELİ (6 Kayıt) ---
  { id: 'ROAD-015', district: 'KORKUTELİ', roadName: 'CENGİZ TOYTUNÇ CADDESİ' },
  { id: 'ROAD-016', district: 'KORKUTELİ', roadName: 'ANTALYA CADDESİ' },
  { id: 'ROAD-017', district: 'KORKUTELİ', roadName: 'FATİH BULVARI 16112015' },
  { id: 'ROAD-018', district: 'KORKUTELİ', roadName: 'İSTİKLAL CADDESİ (ESKİ ELMALI YOLU)' },
  { id: 'ROAD-019', district: 'KORKUTELİ', roadName: 'ATATÜRK VE MEHMET AKİF ERSOY CADDESİNİN' },
  { id: 'ROAD-020', district: 'KORKUTELİ', roadName: 'KAZIM KARABEKİR CADDESİ' },

  // --- KEPEZ (34 Kayıt - Grup 1 & 2) ---
  { id: 'ROAD-021', district: 'KEPEZ', roadName: '5036 SOK.(YENİ SANAYİİ İÇİ)' },
  { id: 'ROAD-022', district: 'KEPEZ', roadName: '4359 SK. (HÜRRİYET CD.-CEZAEVİ YOLU)' },
  { id: 'ROAD-023', district: 'KEPEZ', roadName: '75.YIL CADDESİ' },
  { id: 'ROAD-024', district: 'KEPEZ', roadName: '5044 SOK.( YENİ SANAYİİ İÇİ)' },
  { id: 'ROAD-025', district: 'KEPEZ', roadName: '5061 SOK. ( YENİ SANAYİİ İÇİ)' },
  { id: 'ROAD-026', district: 'KEPEZ', roadName: '5009 SOK.(YENİ SANAYİİ İÇİ)' },
  { id: 'ROAD-027', district: 'KEPEZ', roadName: 'ADNAN SELEKLER CADDESİ' },
  { id: 'ROAD-028', district: 'KEPEZ', roadName: 'BARIŞ MANÇO BULVARI' },
  { id: 'ROAD-029', district: 'KEPEZ', roadName: 'DÜDEN ÇAYI KANAL YOLU' },
  { id: 'ROAD-030', district: 'KEPEZ', roadName: 'FİKRİ ERTEN CADDESİ' },
  { id: 'ROAD-031', district: 'KEPEZ', roadName: 'HURDACILAR CADDESİ' },
  { id: 'ROAD-032', district: 'KEPEZ', roadName: 'M.AKİF CADDESİ' },
  { id: 'ROAD-033', district: 'KEPEZ', roadName: 'MİTHATPAŞA CADDESİ' },
  { id: 'ROAD-034', district: 'KEPEZ', roadName: 'NAMIK KEMAL BULVARI' },
  { id: 'ROAD-035', district: 'KEPEZ', roadName: 'SAKARYA BULVARI' },
  { id: 'ROAD-036', district: 'KEPEZ', roadName: 'ULUSOY CADDESİ' },
  { id: 'ROAD-037', district: 'KEPEZ', roadName: 'YILDIRIM BEYAZIT CADDESİ' },
  { id: 'ROAD-038', district: 'KEPEZ', roadName: '2452 SOKAK' },
  { id: 'ROAD-039', district: 'KEPEZ', roadName: '2553. SOKAK' },
  { id: 'ROAD-040', district: 'KEPEZ', roadName: 'ALTINOVA CADDESİ' },
  { id: 'ROAD-041', district: 'KEPEZ', roadName: 'ANTALYA CADDESİ' },
  { id: 'ROAD-042', district: 'KEPEZ', roadName: 'CEYHAN CADDESİ' },
  { id: 'ROAD-043', district: 'KEPEZ', roadName: 'DÜDEN ÇAYI YOLU 2. BÖLÜM 1. KISIM' },
  { id: 'ROAD-044', district: 'KEPEZ', roadName: 'DÜDEN ÇAYI 2. KISIM 2. BÖLÜM' },
  { id: 'ROAD-045', district: 'KEPEZ', roadName: 'GÖKSU CADDESİ VE 2428 SOKAK' },
  { id: 'ROAD-046', district: 'KEPEZ', roadName: 'KIRÇİÇEĞİ CADDESİ' },
  { id: 'ROAD-047', district: 'KEPEZ', roadName: 'MEHMET ATAY CADDESİ' },
  { id: 'ROAD-048', district: 'KEPEZ', roadName: 'NECİP FAZIL CADDESİ' },
  { id: 'ROAD-049', district: 'KEPEZ', roadName: 'SEYHAN CADDESİ' },
  { id: 'ROAD-050', district: 'KEPEZ', roadName: 'SÜLEYMAN DEMİREL BULVARI' },
  { id: 'ROAD-051', district: 'KEPEZ', roadName: 'SÜTÇÜLER CADDESİ' },
  { id: 'ROAD-052', district: 'KEPEZ', roadName: 'ŞHT.BNB.ERDOĞAN ÖZDEMİR CADDESİ 4358 SK.' },
  { id: 'ROAD-053', district: 'KEPEZ', roadName: 'TOPTANCI HAL YOLU' },
  { id: 'ROAD-054', district: 'KEPEZ', roadName: 'YEŞİLIRMAK CADDESİ' },

  // --- KONYAALTI (18 Kayıt) ---
  { id: 'ROAD-055', district: 'KONYAALTI', roadName: '7. CADDE(ARAPSUYU CAD)' },
  { id: 'ROAD-056', district: 'KONYAALTI', roadName: '14. CADDE(PINARBAŞI CAD)' },
  { id: 'ROAD-057', district: 'KONYAALTI', roadName: '20. CADDE(ANADOLU CAD.)' },
  { id: 'ROAD-058', district: 'KONYAALTI', roadName: '15.CADDE(TOROSLAR CAD.)' },
  { id: 'ROAD-059', district: 'KONYAALTI', roadName: '1325 SOKAK (EMNİYET CAD.)' },
  { id: 'ROAD-060', district: 'KONYAALTI', roadName: '25. CADDE(EMNİYET CAD.)' },
  { id: 'ROAD-061', district: 'KONYAALTI', roadName: '24. CADDE' },
  { id: 'ROAD-062', district: 'KONYAALTI', roadName: 'UNCALI CADDESİ' },
  { id: 'ROAD-063', district: 'KONYAALTI', roadName: '17.CADDE(ÖĞRETMENLER CAD.)' },
  { id: 'ROAD-064', district: 'KONYAALTI', roadName: '6.CADDE(KUŞKAVAĞI CAD.)' },
  { id: 'ROAD-065', district: 'KONYAALTI', roadName: '5. CADDE(BELEDİYE CAD)' },
  { id: 'ROAD-066', district: 'KONYAALTI', roadName: '35. CADDE(ÜNİVERSİTE CAD)' },
  { id: 'ROAD-067', district: 'KONYAALTI', roadName: '32. CADDE(TOROSLAR CAD.)' },
  { id: 'ROAD-068', district: 'KONYAALTI', roadName: '23. CADDE(ÇAMLIK CAD.)' },
  { id: 'ROAD-069', district: 'KONYAALTI', roadName: '19. CADDE(ANADOLU CAD)' },
  { id: 'ROAD-070', district: 'KONYAALTI', roadName: '22. CADDE(EMNİYET CAD.)' },
  { id: 'ROAD-071', district: 'KONYAALTI', roadName: 'GAZİ MUSTAFA KEMAL BULVARI' },
  { id: 'ROAD-072', district: 'KONYAALTI', roadName: 'ATATÜRK BULVARI' },

  // --- MURATPAŞA (82 Kayıt - Gruplar 1, 2, 3 & 4) ---
  { id: 'ROAD-073', district: 'MURATPAŞA', roadName: '413. SOKAK' },
  { id: 'ROAD-074', district: 'MURATPAŞA', roadName: 'İSMET GÖKŞEN CADDESİ' },
  { id: 'ROAD-075', district: 'MURATPAŞA', roadName: 'HIZIRREİS CADDESİ' },
  { id: 'ROAD-076', district: 'MURATPAŞA', roadName: 'ÇAĞLAYANGİL CADDESİ' },
  { id: 'ROAD-077', district: 'MURATPAŞA', roadName: 'KARDEŞ KENTLER CADDESİ' },
  { id: 'ROAD-078', district: 'MURATPAŞA', roadName: 'RAUF DENKTAŞ CADDESİ' },
  { id: 'ROAD-079', district: 'MURATPAŞA', roadName: 'LARA TURZ. YOLU' },
  { id: 'ROAD-080', district: 'MURATPAŞA', roadName: 'PTT CADDESİ' },
  { id: 'ROAD-081', district: 'MURATPAŞA', roadName: 'HAVAALANI CADDESİ' },
  { id: 'ROAD-082', district: 'MURATPAŞA', roadName: 'BARINAKLAR BULVARI' },
  { id: 'ROAD-083', district: 'MURATPAŞA', roadName: 'TEKELİOĞLU CADDESİ' },
  { id: 'ROAD-084', district: 'MURATPAŞA', roadName: 'BÜLENT ECEVİT BULVARI' },
  { id: 'ROAD-085', district: 'MURATPAŞA', roadName: 'SİNANOĞLU CADDESİ' },
  { id: 'ROAD-086', district: 'MURATPAŞA', roadName: 'PERGE BULVARI' },
  { id: 'ROAD-087', district: 'MURATPAŞA', roadName: 'ÇINARLI CADDESİ' },
  { id: 'ROAD-088', district: 'MURATPAŞA', roadName: 'TERMESSOS BULVARI' },
  { id: 'ROAD-089', district: 'MURATPAŞA', roadName: 'ASPENDOS BULVARI' },
  { id: 'ROAD-090', district: 'MURATPAŞA', roadName: 'AŞIK VEYSEL CADDESİ' },
  { id: 'ROAD-091', district: 'MURATPAŞA', roadName: '1343 SOKAK' },
  { id: 'ROAD-092', district: 'MURATPAŞA', roadName: '1349. SOKAK' },
  { id: 'ROAD-093', district: 'MURATPAŞA', roadName: 'KÖROĞLU CADDESİ' },
  { id: 'ROAD-094', district: 'MURATPAŞA', roadName: 'MEVLANA CADDESİ' },
  { id: 'ROAD-095', district: 'MURATPAŞA', roadName: 'KIZILIRMAK CADDESİ' },
  { id: 'ROAD-096', district: 'MURATPAŞA', roadName: 'EVLİYA ÇELEBİ CADDESİ' },
  { id: 'ROAD-097', district: 'MURATPAŞA', roadName: 'KARACAOĞLAN CADDESİ' },
  { id: 'ROAD-098', district: 'MURATPAŞA', roadName: 'FATİH CADDESİ' },
  { id: 'ROAD-099', district: 'MURATPAŞA', roadName: 'AVNİ TOLUNAY CADDESİ' },
  { id: 'ROAD-100', district: 'MURATPAŞA', roadName: 'NARENCİYE CADDESİ' },
  { id: 'ROAD-101', district: 'MURATPAŞA', roadName: 'METİN KASAPOĞLU CADDESİ' },
  { id: 'ROAD-102', district: 'MURATPAŞA', roadName: 'PORTAKAL ÇİÇEĞİ BULVARI' },
  { id: 'ROAD-103', district: 'MURATPAŞA', roadName: 'BURHANETTİN ONAT CADDESİ' },
  { id: 'ROAD-104', district: 'MURATPAŞA', roadName: 'TEFİK IŞIK CADDESİ' },
  { id: 'ROAD-105', district: 'MURATPAŞA', roadName: 'CEBESOY CADDESİ' },
  { id: 'ROAD-106', district: 'MURATPAŞA', roadName: '19 MAYIS CADDESİ' },
  { id: 'ROAD-107', district: 'MURATPAŞA', roadName: 'IŞIKLAR CADDESİ' },
  { id: 'ROAD-108', district: 'MURATPAŞA', roadName: 'ARIK CADDESİ' },
  { id: 'ROAD-109', district: 'MURATPAŞA', roadName: 'ATATÜRK CADDESİ' },
  { id: 'ROAD-110', district: 'MURATPAŞA', roadName: 'ALİ ÇETİNKAYA CADDESİ' },
  { id: 'ROAD-111', district: 'MURATPAŞA', roadName: '1350. SOKAK' },
  { id: 'ROAD-112', district: 'MURATPAŞA', roadName: '1347. SOKAK' },
  { id: 'ROAD-113', district: 'MURATPAŞA', roadName: '2. İNÖNÜ CADDESİ' },
  { id: 'ROAD-114', district: 'MURATPAŞA', roadName: 'ADNAN MENDERES BULVARİI' },
  { id: 'ROAD-115', district: 'MURATPAŞA', roadName: 'FAHRETTİN ALTAY CADDESİ' },
  { id: 'ROAD-116', district: 'MURATPAŞA', roadName: 'İSMETPAŞA CADDESİ' },
  { id: 'ROAD-117', district: 'MURATPAŞA', roadName: 'ŞARAMPOL CADDESİ' },
  { id: 'ROAD-118', district: 'MURATPAŞA', roadName: 'APDİ İPEKCİ CADDESİ' },
  { id: 'ROAD-119', district: 'MURATPAŞA', roadName: 'VATAN BULVARI' },
  { id: 'ROAD-120', district: 'MURATPAŞA', roadName: 'HASAN SUBAŞI CADDESİ' },
  { id: 'ROAD-121', district: 'MURATPAŞA', roadName: 'ŞHT. BİNBAŞI CENGİZ TOYTUNÇ CADDESİ' },
  { id: 'ROAD-122', district: 'MURATPAŞA', roadName: 'MİLLİ EGEMENLİK CADDESİ' },
  { id: 'ROAD-123', district: 'MURATPAŞA', roadName: 'YENER ULUSOY BULVARİI' },
  { id: 'ROAD-124', district: 'MURATPAŞA', roadName: 'CUMHURİYET CADDESİ' },
  { id: 'ROAD-125', district: 'MURATPAŞA', roadName: '281 SOKAK' },
  { id: 'ROAD-126', district: 'MURATPAŞA', roadName: 'GÜLLÜK CADDESİ' },
  { id: 'ROAD-127', district: 'MURATPAŞA', roadName: 'TONGUÇ CADDESİ' },
  { id: 'ROAD-128', district: 'MURATPAŞA', roadName: 'TURGUT REİS CADDESİ(ZİNCİRKİRAN CAD)' },
  { id: 'ROAD-129', district: 'MURATPAŞA', roadName: 'KONYAALTI CADDESİ' },
  { id: 'ROAD-130', district: 'MURATPAŞA', roadName: 'TEOMANPAŞA CADDESİ' },
  { id: 'ROAD-131', district: 'MURATPAŞA', roadName: '493. SOKAK' },
  { id: 'ROAD-132', district: 'MURATPAŞA', roadName: 'GÜLLÜPINAR CADDESİ' },
  { id: 'ROAD-133', district: 'MURATPAŞA', roadName: 'F.OKYAR CADDESİ' },
  { id: 'ROAD-134', district: 'MURATPAŞA', roadName: 'PİRİREİS CADDESİ' },
  { id: 'ROAD-135', district: 'MURATPAŞA', roadName: 'DEFTERDARLIK BULVARI' },
  { id: 'ROAD-136', district: 'MURATPAŞA', roadName: '100.YIL BULVARI' },
  { id: 'ROAD-137', district: 'MURATPAŞA', roadName: 'YILDIZ CADDESİ' },
  { id: 'ROAD-138', district: 'MURATPAŞA', roadName: 'KAZIM KARABEKİR CADDESİ' },
  { id: 'ROAD-139', district: 'MURATPAŞA', roadName: 'PINAR CADDESİ' },
  { id: 'ROAD-140', district: 'MURATPAŞA', roadName: 'MELTEM BULVARI' },
  { id: 'ROAD-141', district: 'MURATPAŞA', roadName: 'TARIK AKILTOPU CADDESİ' },
  { id: 'ROAD-142', district: 'MURATPAŞA', roadName: 'SABANCI BULVARI' },
  { id: 'ROAD-143', district: 'MURATPAŞA', roadName: 'ESKİ ŞARAMPOL CADDESİ' },
  { id: 'ROAD-144', district: 'MURATPAŞA', roadName: '90. SOKAK' },
  { id: 'ROAD-145', district: 'MURATPAŞA', roadName: '620. SOKAK' },
  { id: 'ROAD-146', district: 'MURATPAŞA', roadName: '567. SOKAK' },
  { id: 'ROAD-147', district: 'MURATPAŞA', roadName: '10. SOKAK' },
  { id: 'ROAD-148', district: 'MURATPAŞA', roadName: '1339. SOKAK' },
  { id: 'ROAD-149', district: 'MURATPAŞA', roadName: '1346. SOKAK' },
  { id: 'ROAD-150', district: 'MURATPAŞA', roadName: '1348. SOKAK' },
  { id: 'ROAD-151', district: 'MURATPAŞA', roadName: '1340. SOKAK' },
  { id: 'ROAD-152', district: 'MURATPAŞA', roadName: '1345. SOKAK' },
  { id: 'ROAD-153', district: 'MURATPAŞA', roadName: '516 SOKAK' },
  { id: 'ROAD-154', district: 'MURATPAŞA', roadName: '489 SOKAK' },
];

/**
 * PDF Kaynak Doğrulama Metrikleri:
 * Toplam PDF Kayıt Sayısı: 154
 * İlçe Dağılımı:
 * - AKSU: 10
 * - DÖŞEMEALTI: 1
 * - SERİK: 3
 * - KORKUTELİ: 6
 * - KEPEZ: 34
 * - KONYAALTI: 18
 * - MURATPAŞA: 82
 */
export const EXPECTED_PDF_RECORD_COUNT = 154;
export const EXPECTED_DISTRICT_COUNTS: Record<string, number> = {
  AKSU: 10,
  DÖŞEMEALTI: 1,
  SERİK: 3,
  KORKUTELİ: 6,
  KEPEZ: 34,
  KONYAALTI: 18,
  MURATPAŞA: 82,
};
