import { FieldTeam, EneryaEmployee, ControlCompany, ControlEmployee } from '@/types';

export const mockEneryaEmployees: EneryaEmployee[] = [
  { id: 'E1', name: 'Ahmet Yılmaz' },
  { id: 'E2', name: 'Mehmet Demir' },
  { id: 'E3', name: 'Hasan Kaya' },
  { id: 'E4', name: 'Burak Çelik' },
  { id: 'E5', name: 'Ali Yıldız' },
  { id: 'E6', name: 'Veli Şahin' },
  { id: 'E7', name: 'Can Öztürk' },
  { id: 'E8', name: 'Kerem Aslan' },
  { id: 'E9', name: 'Mustafa Korkmaz' },
  { id: 'E10', name: 'Kadir Erdoğan' },
];

export const mockControlCompanies: ControlCompany[] = [
  { id: 'C1', name: 'ABC Kontrol A.Ş.' },
  { id: 'C2', name: 'XYZ Yapı Kontrol' },
  { id: 'C3', name: 'Delta Kontrol' },
  { id: 'C4', name: 'Gama Mühendislik' },
];

export const mockControlEmployees: ControlEmployee[] = [
  { id: 'CE1', companyId: 'C1', name: 'Mehmet Kaya' },
  { id: 'CE2', companyId: 'C1', name: 'Ali Demir' },
  { id: 'CE3', companyId: 'C1', name: 'Can Yıldız' },
  { id: 'CE4', companyId: 'C1', name: 'Bora Aksoy' },
  { id: 'CE5', companyId: 'C2', name: 'Selim Taşkın' },
  { id: 'CE6', companyId: 'C2', name: 'Onur Tekin' },
  { id: 'CE7', companyId: 'C2', name: 'Emre Başar' },
  { id: 'CE8', companyId: 'C2', name: 'Turan Çelik' },
  { id: 'CE9', companyId: 'C3', name: 'Fatih Gündüz' },
  { id: 'CE10', companyId: 'C3', name: 'Kemal Sunal' },
  { id: 'CE11', companyId: 'C3', name: 'Hakan Yılmaz' },
  { id: 'CE12', companyId: 'C4', name: 'Cem Uzan' },
  { id: 'CE13', companyId: 'C4', name: 'Tarık Akan' },
  { id: 'CE14', companyId: 'C4', name: 'Mert Mert' },
  { id: 'CE15', companyId: 'C4', name: 'Okan Okan' },
];

export const mockLocations = {
  'Kepez': ['Yükseliş', 'Varsak', 'Fabrikalar', 'Ahatlı', 'Kültür'],
  'Muratpaşa': ['Lara', 'Şirinyalı', 'Kızıltoprak', 'Meydankavağı', 'Güzeloba'],
  'Konyaaltı': ['Liman', 'Hurma', 'Arapsuyu', 'Gürsu', 'Uncalı'],
  'Döşemealtı': ['Yeniköy', 'Yeşilbayır', 'Çıplaklı'],
  'Aksu': ['Macun', 'Çalkaya', 'Pınarlı'],
};

const getEmployee = (id: string) => mockEneryaEmployees.find(e => e.id === id)!;
const getCompany = (id: string) => mockControlCompanies.find(c => c.id === id)!;
const getControlEmp = (id: string) => mockControlEmployees.find(ce => ce.id === id)!;

export const mockTeams: FieldTeam[] = [
  {
    id: 'T1',
    code: 'Ekip 01',
    eneryaEmployee: getEmployee('E1'),
    controlCompany: getCompany('C1'),
    controlEmployee: getControlEmp('CE1'),
    district: 'Kepez',
    neighborhood: 'Yükseliş',
    workType: 'PE Ana Hat',
    serviceBoxIds: ['1', '2', '3'],
    status: 'Aktif',
    assignmentDate: '2026-09-21',
    updatedAt: '2026-09-22T08:30:00Z',
    lat: 36.9114,
    lng: 30.6865,
  },
  {
    id: 'T2',
    code: 'Ekip 02',
    eneryaEmployee: getEmployee('E2'),
    controlCompany: getCompany('C2'),
    controlEmployee: getControlEmp('CE5'),
    district: 'Muratpaşa',
    neighborhood: 'Lara',
    workType: 'Servis Hattı',
    serviceBoxIds: ['4', '5'],
    status: 'Bekliyor',
    assignmentDate: '2026-09-22',
    updatedAt: '2026-09-22T09:15:00Z',
    lat: 36.8529,
    lng: 30.7495,
  },
  {
    id: 'T3',
    code: 'Ekip 03',
    eneryaEmployee: getEmployee('E3'),
    controlCompany: getCompany('C3'),
    controlEmployee: getControlEmp('CE9'),
    district: 'Konyaaltı',
    neighborhood: 'Liman',
    workType: 'ST Çelik Hat',
    serviceBoxIds: ['6', '7', '8', '9'],
    status: 'Aktif',
    assignmentDate: '2026-09-20',
    updatedAt: '2026-09-22T10:00:00Z',
    lat: 36.8286,
    lng: 30.6074,
  },
  {
    id: 'T4',
    code: 'Ekip 04',
    eneryaEmployee: getEmployee('E4'),
    controlCompany: getCompany('C4'),
    controlEmployee: getControlEmp('CE12'),
    district: 'Döşemealtı',
    neighborhood: 'Yeniköy',
    workType: 'Servis Kutusu',
    serviceBoxIds: ['10', '11'],
    status: 'Tamamlandı',
    assignmentDate: '2026-09-18',
    updatedAt: '2026-09-19T17:30:00Z',
    lat: 37.0142,
    lng: 30.5694,
  },
  {
    id: 'T5',
    code: 'Ekip 05',
    eneryaEmployee: getEmployee('E5'),
    controlCompany: getCompany('C1'),
    controlEmployee: getControlEmp('CE2'),
    district: 'Kepez',
    neighborhood: 'Varsak',
    workType: 'PE Ana Hat',
    serviceBoxIds: ['12', '13', '14'],
    status: 'Aktif',
    assignmentDate: '2026-09-22',
    updatedAt: '2026-09-22T11:00:00Z',
    lat: 36.9538,
    lng: 30.7247,
  },
  {
    id: 'T6',
    code: 'Ekip 06',
    eneryaEmployee: getEmployee('E6'),
    controlCompany: getCompany('C2'),
    controlEmployee: getControlEmp('CE6'),
    district: 'Aksu',
    neighborhood: 'Macun',
    workType: 'Servis Hattı',
    serviceBoxIds: ['15'],
    status: 'Bekliyor',
    assignmentDate: '2026-09-22',
    updatedAt: '2026-09-22T08:00:00Z',
    lat: 36.9372,
    lng: 30.8521,
  },
  {
    id: 'T7',
    code: 'Ekip 07',
    eneryaEmployee: getEmployee('E7'),
    controlCompany: getCompany('C3'),
    controlEmployee: getControlEmp('CE10'),
    district: 'Muratpaşa',
    neighborhood: 'Şirinyalı',
    workType: 'ST Çelik Hat',
    serviceBoxIds: ['16', '17'],
    status: 'Aktif',
    assignmentDate: '2026-09-21',
    updatedAt: '2026-09-22T12:00:00Z',
  },
  {
    id: 'T8',
    code: 'Ekip 08',
    eneryaEmployee: getEmployee('E8'),
    controlCompany: getCompany('C4'),
    controlEmployee: getControlEmp('CE13'),
    district: 'Konyaaltı',
    neighborhood: 'Hurma',
    workType: 'Servis Kutusu',
    serviceBoxIds: ['18', '19', '20'],
    status: 'Tamamlandı',
    assignmentDate: '2026-09-15',
    updatedAt: '2026-09-16T18:00:00Z',
  },
  {
    id: 'T9',
    code: 'Ekip 09',
    eneryaEmployee: getEmployee('E9'),
    controlCompany: getCompany('C1'),
    controlEmployee: getControlEmp('CE3'),
    district: 'Kepez',
    neighborhood: 'Fabrikalar',
    workType: 'PE Ana Hat',
    serviceBoxIds: ['21', '22'],
    status: 'Aktif',
    assignmentDate: '2026-09-22',
    updatedAt: '2026-09-22T13:30:00Z',
  },
  {
    id: 'T10',
    code: 'Ekip 10',
    eneryaEmployee: getEmployee('E10'),
    controlCompany: getCompany('C2'),
    controlEmployee: getControlEmp('CE7'),
    district: 'Muratpaşa',
    neighborhood: 'Kızıltoprak',
    workType: 'Servis Hattı',
    serviceBoxIds: ['23', '24'],
    status: 'Bekliyor',
    assignmentDate: '2026-09-22',
    updatedAt: '2026-09-22T08:15:00Z',
  }
];
